server:
  JwtSecretKey: secretKey

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: anton
  PostgresqlPassword: my_password
  PostgresqlDbname: emstaht
  PostgresqlSslmode: disable
