basePath: /api/v1
definitions:
  dto.RegisterRequest:
    properties:
      dob:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is my project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Emstaht
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers new user
      parameters:
      - description: RegisterJson
        in: body
        name: userDto
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Register new user
      tags:
      - auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
